volumes:
    prometheus_data: {}
    grafana_data: {}
    extravawall_db_data: {}

networks:
  extravawall-network-internal:
    name: extravawall-network-internal
    driver: bridge

services:
  extravawall-web-service:
    container_name: extravawall-web
    image: localhost/extravawall-web:latest
    #build: .
    #command: dotnet publish --os linux --arch x64 /t:PublishContainer -c Release
    restart: unless-stopped
    networks:
      - extravawall-network-internal
    ports:
      - 5001:8080
    depends_on:
      - extravawall-db-service
  
  extravawall-prometheus-service:
    container_name: extravawall-prometheus
    image: docker.io/prom/prometheus:v2.48.0
    networks:
      - extravawall-network-internal
    ports:
      - 9090:9090
    volumes:
      - ./container-files/prometheus:/etc/prometheus:Z
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - extravawall-web-service
    restart: unless-stopped
  
  extravawall-grafana-service:
    container_name: extravawall-grafana
    image: docker.io/grafana/grafana-oss:10.2.2
    networks:
      - extravawall-network-internal
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./container-files/grafana:/etc/grafana:Z
    depends_on: 
      - extravawall-prometheus-service
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=volkovlabs-echarts-panel
  
  extravawall-db-service:
    container_name: extravawall-db
    image: docker.io/dolthub/dolt-sql-server:1.28.1
    networks:
      - extravawall-network-internal
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
    #  - ./container-files/doit/servercfg:/etc/dolt/servercfg.d:Z
    #  - ./container-files/doit/doltcfg:/etc/dolt/doltcfg.d:Z
      - extravawall_db_data:/var/lib/dolt
    #environment:

